// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.24.4
// source: log_service.proto

package logpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	LogUploadService_UploadLogBatch_FullMethodName    = "/logcollector.LogUploadService/UploadLogBatch"
	LogUploadService_StreamUploadLog_FullMethodName   = "/logcollector.LogUploadService/StreamUploadLog"
	LogUploadService_PullAttentionList_FullMethodName = "/logcollector.LogUploadService/PullAttentionList"
	LogUploadService_Heartbeat_FullMethodName         = "/logcollector.LogUploadService/Heartbeat"
)

// LogUploadServiceClient is the client API for LogUploadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============================================================
// 日志上传服务 - Agent → Center
// ============================================================
type LogUploadServiceClient interface {
	// 批量上传日志条目
	UploadLogBatch(ctx context.Context, in *UploadLogBatchRequest, opts ...grpc.CallOption) (*UploadLogBatchResponse, error)
	// 流式上传（大批量场景）
	StreamUploadLog(ctx context.Context, opts ...grpc.CallOption) (LogUploadService_StreamUploadLogClient, error)
	// 拉取当前关注清单
	PullAttentionList(ctx context.Context, in *PullAttentionListRequest, opts ...grpc.CallOption) (*PullAttentionListResponse, error)
	// 心跳上报（含节点资源状态）
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type logUploadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogUploadServiceClient(cc grpc.ClientConnInterface) LogUploadServiceClient {
	return &logUploadServiceClient{cc}
}

func (c *logUploadServiceClient) UploadLogBatch(ctx context.Context, in *UploadLogBatchRequest, opts ...grpc.CallOption) (*UploadLogBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadLogBatchResponse)
	err := c.cc.Invoke(ctx, LogUploadService_UploadLogBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logUploadServiceClient) StreamUploadLog(ctx context.Context, opts ...grpc.CallOption) (LogUploadService_StreamUploadLogClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogUploadService_ServiceDesc.Streams[0], LogUploadService_StreamUploadLog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &logUploadServiceStreamUploadLogClient{ClientStream: stream}
	return x, nil
}

type LogUploadService_StreamUploadLogClient interface {
	Send(*LogEntry) error
	CloseAndRecv() (*UploadLogBatchResponse, error)
	grpc.ClientStream
}

type logUploadServiceStreamUploadLogClient struct {
	grpc.ClientStream
}

func (x *logUploadServiceStreamUploadLogClient) Send(m *LogEntry) error {
	return x.ClientStream.SendMsg(m)
}

func (x *logUploadServiceStreamUploadLogClient) CloseAndRecv() (*UploadLogBatchResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadLogBatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *logUploadServiceClient) PullAttentionList(ctx context.Context, in *PullAttentionListRequest, opts ...grpc.CallOption) (*PullAttentionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullAttentionListResponse)
	err := c.cc.Invoke(ctx, LogUploadService_PullAttentionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logUploadServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, LogUploadService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogUploadServiceServer is the server API for LogUploadService service.
// All implementations must embed UnimplementedLogUploadServiceServer
// for forward compatibility
//
// ============================================================
// 日志上传服务 - Agent → Center
// ============================================================
type LogUploadServiceServer interface {
	// 批量上传日志条目
	UploadLogBatch(context.Context, *UploadLogBatchRequest) (*UploadLogBatchResponse, error)
	// 流式上传（大批量场景）
	StreamUploadLog(LogUploadService_StreamUploadLogServer) error
	// 拉取当前关注清单
	PullAttentionList(context.Context, *PullAttentionListRequest) (*PullAttentionListResponse, error)
	// 心跳上报（含节点资源状态）
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedLogUploadServiceServer()
}

// UnimplementedLogUploadServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLogUploadServiceServer struct {
}

func (UnimplementedLogUploadServiceServer) UploadLogBatch(context.Context, *UploadLogBatchRequest) (*UploadLogBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadLogBatch not implemented")
}
func (UnimplementedLogUploadServiceServer) StreamUploadLog(LogUploadService_StreamUploadLogServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamUploadLog not implemented")
}
func (UnimplementedLogUploadServiceServer) PullAttentionList(context.Context, *PullAttentionListRequest) (*PullAttentionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullAttentionList not implemented")
}
func (UnimplementedLogUploadServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedLogUploadServiceServer) mustEmbedUnimplementedLogUploadServiceServer() {}

// UnsafeLogUploadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogUploadServiceServer will
// result in compilation errors.
type UnsafeLogUploadServiceServer interface {
	mustEmbedUnimplementedLogUploadServiceServer()
}

func RegisterLogUploadServiceServer(s grpc.ServiceRegistrar, srv LogUploadServiceServer) {
	s.RegisterService(&LogUploadService_ServiceDesc, srv)
}

func _LogUploadService_UploadLogBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadLogBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogUploadServiceServer).UploadLogBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogUploadService_UploadLogBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogUploadServiceServer).UploadLogBatch(ctx, req.(*UploadLogBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogUploadService_StreamUploadLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogUploadServiceServer).StreamUploadLog(&logUploadServiceStreamUploadLogServer{ServerStream: stream})
}

type LogUploadService_StreamUploadLogServer interface {
	SendAndClose(*UploadLogBatchResponse) error
	Recv() (*LogEntry, error)
	grpc.ServerStream
}

type logUploadServiceStreamUploadLogServer struct {
	grpc.ServerStream
}

func (x *logUploadServiceStreamUploadLogServer) SendAndClose(m *UploadLogBatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *logUploadServiceStreamUploadLogServer) Recv() (*LogEntry, error) {
	m := new(LogEntry)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _LogUploadService_PullAttentionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullAttentionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogUploadServiceServer).PullAttentionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogUploadService_PullAttentionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogUploadServiceServer).PullAttentionList(ctx, req.(*PullAttentionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogUploadService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogUploadServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogUploadService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogUploadServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogUploadService_ServiceDesc is the grpc.ServiceDesc for LogUploadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogUploadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logcollector.LogUploadService",
	HandlerType: (*LogUploadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadLogBatch",
			Handler:    _LogUploadService_UploadLogBatch_Handler,
		},
		{
			MethodName: "PullAttentionList",
			Handler:    _LogUploadService_PullAttentionList_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _LogUploadService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUploadLog",
			Handler:       _LogUploadService_StreamUploadLog_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "log_service.proto",
}
