// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.24.4
// source: rule_service.proto

package logpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	RuleDispatchService_PushRules_FullMethodName            = "/logcollector.RuleDispatchService/PushRules"
	RuleDispatchService_BroadcastRules_FullMethodName       = "/logcollector.RuleDispatchService/BroadcastRules"
	RuleDispatchService_SubscribeRuleUpdates_FullMethodName = "/logcollector.RuleDispatchService/SubscribeRuleUpdates"
	RuleDispatchService_ReportActiveRules_FullMethodName    = "/logcollector.RuleDispatchService/ReportActiveRules"
)

// RuleDispatchServiceClient is the client API for RuleDispatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============================================================
// 规则下发服务 - Center → Agent
// ============================================================
type RuleDispatchServiceClient interface {
	// 推送规则到指定节点
	PushRules(ctx context.Context, in *PushRulesRequest, opts ...grpc.CallOption) (*PushRulesResponse, error)
	// 广播规则到所有节点（Center 内部调用）
	BroadcastRules(ctx context.Context, in *BroadcastRulesRequest, opts ...grpc.CallOption) (*BroadcastRulesResponse, error)
	// 订阅规则变更流（Agent 长连接）
	SubscribeRuleUpdates(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (RuleDispatchService_SubscribeRuleUpdatesClient, error)
	// 上报当前生效的规则（Agent → Center，用于一致性校验）
	ReportActiveRules(ctx context.Context, in *ReportActiveRulesRequest, opts ...grpc.CallOption) (*ReportActiveRulesResponse, error)
}

type ruleDispatchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuleDispatchServiceClient(cc grpc.ClientConnInterface) RuleDispatchServiceClient {
	return &ruleDispatchServiceClient{cc}
}

func (c *ruleDispatchServiceClient) PushRules(ctx context.Context, in *PushRulesRequest, opts ...grpc.CallOption) (*PushRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushRulesResponse)
	err := c.cc.Invoke(ctx, RuleDispatchService_PushRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleDispatchServiceClient) BroadcastRules(ctx context.Context, in *BroadcastRulesRequest, opts ...grpc.CallOption) (*BroadcastRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastRulesResponse)
	err := c.cc.Invoke(ctx, RuleDispatchService_BroadcastRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleDispatchServiceClient) SubscribeRuleUpdates(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (RuleDispatchService_SubscribeRuleUpdatesClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuleDispatchService_ServiceDesc.Streams[0], RuleDispatchService_SubscribeRuleUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &ruleDispatchServiceSubscribeRuleUpdatesClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RuleDispatchService_SubscribeRuleUpdatesClient interface {
	Recv() (*RuleUpdate, error)
	grpc.ClientStream
}

type ruleDispatchServiceSubscribeRuleUpdatesClient struct {
	grpc.ClientStream
}

func (x *ruleDispatchServiceSubscribeRuleUpdatesClient) Recv() (*RuleUpdate, error) {
	m := new(RuleUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ruleDispatchServiceClient) ReportActiveRules(ctx context.Context, in *ReportActiveRulesRequest, opts ...grpc.CallOption) (*ReportActiveRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportActiveRulesResponse)
	err := c.cc.Invoke(ctx, RuleDispatchService_ReportActiveRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleDispatchServiceServer is the server API for RuleDispatchService service.
// All implementations must embed UnimplementedRuleDispatchServiceServer
// for forward compatibility
//
// ============================================================
// 规则下发服务 - Center → Agent
// ============================================================
type RuleDispatchServiceServer interface {
	// 推送规则到指定节点
	PushRules(context.Context, *PushRulesRequest) (*PushRulesResponse, error)
	// 广播规则到所有节点（Center 内部调用）
	BroadcastRules(context.Context, *BroadcastRulesRequest) (*BroadcastRulesResponse, error)
	// 订阅规则变更流（Agent 长连接）
	SubscribeRuleUpdates(*SubscribeRequest, RuleDispatchService_SubscribeRuleUpdatesServer) error
	// 上报当前生效的规则（Agent → Center，用于一致性校验）
	ReportActiveRules(context.Context, *ReportActiveRulesRequest) (*ReportActiveRulesResponse, error)
	mustEmbedUnimplementedRuleDispatchServiceServer()
}

// UnimplementedRuleDispatchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRuleDispatchServiceServer struct {
}

func (UnimplementedRuleDispatchServiceServer) PushRules(context.Context, *PushRulesRequest) (*PushRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushRules not implemented")
}
func (UnimplementedRuleDispatchServiceServer) BroadcastRules(context.Context, *BroadcastRulesRequest) (*BroadcastRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastRules not implemented")
}
func (UnimplementedRuleDispatchServiceServer) SubscribeRuleUpdates(*SubscribeRequest, RuleDispatchService_SubscribeRuleUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeRuleUpdates not implemented")
}
func (UnimplementedRuleDispatchServiceServer) ReportActiveRules(context.Context, *ReportActiveRulesRequest) (*ReportActiveRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportActiveRules not implemented")
}
func (UnimplementedRuleDispatchServiceServer) mustEmbedUnimplementedRuleDispatchServiceServer() {}

// UnsafeRuleDispatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuleDispatchServiceServer will
// result in compilation errors.
type UnsafeRuleDispatchServiceServer interface {
	mustEmbedUnimplementedRuleDispatchServiceServer()
}

func RegisterRuleDispatchServiceServer(s grpc.ServiceRegistrar, srv RuleDispatchServiceServer) {
	s.RegisterService(&RuleDispatchService_ServiceDesc, srv)
}

func _RuleDispatchService_PushRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleDispatchServiceServer).PushRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleDispatchService_PushRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleDispatchServiceServer).PushRules(ctx, req.(*PushRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleDispatchService_BroadcastRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleDispatchServiceServer).BroadcastRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleDispatchService_BroadcastRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleDispatchServiceServer).BroadcastRules(ctx, req.(*BroadcastRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleDispatchService_SubscribeRuleUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuleDispatchServiceServer).SubscribeRuleUpdates(m, &ruleDispatchServiceSubscribeRuleUpdatesServer{ServerStream: stream})
}

type RuleDispatchService_SubscribeRuleUpdatesServer interface {
	Send(*RuleUpdate) error
	grpc.ServerStream
}

type ruleDispatchServiceSubscribeRuleUpdatesServer struct {
	grpc.ServerStream
}

func (x *ruleDispatchServiceSubscribeRuleUpdatesServer) Send(m *RuleUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _RuleDispatchService_ReportActiveRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportActiveRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleDispatchServiceServer).ReportActiveRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleDispatchService_ReportActiveRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleDispatchServiceServer).ReportActiveRules(ctx, req.(*ReportActiveRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuleDispatchService_ServiceDesc is the grpc.ServiceDesc for RuleDispatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuleDispatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logcollector.RuleDispatchService",
	HandlerType: (*RuleDispatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushRules",
			Handler:    _RuleDispatchService_PushRules_Handler,
		},
		{
			MethodName: "BroadcastRules",
			Handler:    _RuleDispatchService_BroadcastRules_Handler,
		},
		{
			MethodName: "ReportActiveRules",
			Handler:    _RuleDispatchService_ReportActiveRules_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeRuleUpdates",
			Handler:       _RuleDispatchService_SubscribeRuleUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rule_service.proto",
}
